INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (1, 'Afghanistan', 'AF', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (2, 'Åland Islands', 'AX', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (3, 'Albania', 'AL', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (4, 'Algeria', 'DZ', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (5, 'American Samoa', 'AS', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (6, 'Andorra', 'AD', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (7, 'Angola', 'AO', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (8, 'Anguilla', 'AI', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (9, 'Antarctica', 'AQ', 2);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (10, 'Antigua and Barbuda', 'AG', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (11, 'Argentina', 'AR', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (12, 'Armenia', 'AM', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (13, 'Aruba', 'AW', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (14, 'Australia', 'AU', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (15, 'Austria', 'AT', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (16, 'Azerbaijan', 'AZ', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (17, 'Bahamas', 'BS', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (18, 'Bahrain', 'BH', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (19, 'Bangladesh', 'BD', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (20, 'Barbados', 'BB', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (21, 'Belarus', 'BY', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (22, 'Belgium', 'BE', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (23, 'Belize', 'BZ', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (24, 'Benin', 'BJ', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (25, 'Bermuda', 'BM', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (26, 'Bhutan', 'BT', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (27, 'Bolivia', 'BO', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (28, 'Bonaire, Sint Eustatius and Saba', 'BQ', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (29, 'Bosnia and Herzegovina', 'BA', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (30, 'Botswana', 'BW', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (31, 'Bouvet Island', 'BV', 2);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (32, 'Brazil', 'BR', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (33, 'British Indian Ocean Territory', 'IO', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (34, 'Brunei Darussalam', 'BN', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (35, 'Bulgaria', 'BG', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (36, 'Burkina Faso', 'BF', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (37, 'Burundi', 'BI', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (38, 'Cambodia', 'KH', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (39, 'Cameroon', 'CM', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (40, 'Canada', 'CA', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (41, 'Cape Verde', 'CV', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (42, 'Cayman Islands', 'KY', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (43, 'Central African Republic', 'CF', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (44, 'Chad', 'TD', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (45, 'Chile', 'CL', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (46, 'China', 'CN', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (47, 'Christmas Island', 'CX', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (48, 'Cocos (Keeling) Islands', 'CC', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (49, 'Colombia', 'CO', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (50, 'Comoros', 'KM', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (51, 'Congo', 'CG', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (52, 'Congo, the Democratic Republic of the', 'CD', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (53, 'Cook Islands', 'CK', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (54, 'Costa Rica', 'CR', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (55, 'Côte d\'Ivoire', 'CI', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (56, 'Croatia', 'HR', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (57, 'Cuba', 'CU', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (58, 'Curaçao', 'CW', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (59, 'Cyprus', 'CY', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (60, 'Czech Republic', 'CZ', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (61, 'Denmark', 'DK', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (62, 'Djibouti', 'DJ', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (63, 'Dominica', 'DM', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (64, 'Dominican Republic', 'DO', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (65, 'Ecuador', 'EC', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (66, 'Egypt', 'EG', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (67, 'El Salvador', 'SV', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (68, 'Equatorial Guinea', 'GQ', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (69, 'Eritrea', 'ER', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (70, 'Estonia', 'EE', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (71, 'Ethiopia', 'ET', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (72, 'Falkland Islands (Malvinas)', 'FK', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (73, 'Faroe Islands', 'FO', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (74, 'Fiji', 'FJ', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (75, 'Finland', 'FI', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (76, 'France', 'FR', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (77, 'French Guiana', 'GF', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (78, 'French Polynesia', 'PF', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (79, 'French Southern Territories', 'TF', 2);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (80, 'Gabon', 'GA', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (81, 'Gambia', 'GM', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (82, 'Georgia', 'GE', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (83, 'Germany', 'DE', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (84, 'Ghana', 'GH', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (85, 'Gibraltar', 'GI', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (86, 'Greece', 'GR', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (87, 'Greenland', 'GL', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (88, 'Grenada', 'GD', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (89, 'Guadeloupe', 'GP', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (90, 'Guam', 'GU', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (91, 'Guatemala', 'GT', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (92, 'Guernsey', 'GG', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (93, 'Guinea', 'GN', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (94, 'Guinea-Bissau', 'GW', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (95, 'Guyana', 'GY', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (96, 'Haiti', 'HT', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (97, 'Heard Island and McDonald Islands', 'HM', 2);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (98, 'Holy See (Vatican City State)', 'VA', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (99, 'Honduras', 'HN', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (100, 'Hong Kong', 'HK', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (101, 'Hungary', 'HU', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (102, 'Iceland', 'IS', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (103, 'India', 'IN', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (104, 'Indonesia', 'ID', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (105, 'Iran, Islamic Republic of', 'IR', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (106, 'Iraq', 'IQ', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (107, 'Ireland', 'IE', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (108, 'Isle of Man', 'IM', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (109, 'Israel', 'IL', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (110, 'Italy', 'IT', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (111, 'Jamaica', 'JM', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (112, 'Japan', 'JP', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (113, 'Jersey', 'JE', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (114, 'Jordan', 'JO', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (115, 'Kazakhstan', 'KZ', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (116, 'Kenya', 'KE', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (117, 'Kiribati', 'KI', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (118, 'Korea, Democratic People\'s Republic of', 'KP', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (119, 'Korea, Republic of', 'KR', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (120, 'Kuwait', 'KW', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (121, 'Kyrgyzstan', 'KG', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (122, 'Lao People\'s Democratic Republic', 'LA', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (123, 'Latvia', 'LV', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (124, 'Lebanon', 'LB', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (125, 'Lesotho', 'LS', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (126, 'Liberia', 'LR', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (127, 'Libyan Arab Jamahiriya', 'LY', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (128, 'Liechtenstein', 'LI', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (129, 'Lithuania', 'LT', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (130, 'Luxembourg', 'LU', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (131, 'Macao', 'MO', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (132, 'Macedonia, the Former Yugoslav Republic of', 'MK', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (133, 'Madagascar', 'MG', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (134, 'Malawi', 'MW', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (135, 'Malaysia', 'MY', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (136, 'Maldives', 'MV', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (137, 'Mali', 'ML', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (138, 'Malta', 'MT', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (139, 'Marshall Islands', 'MH', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (140, 'Martinique', 'MQ', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (141, 'Mauritania', 'MR', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (142, 'Mauritius', 'MU', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (143, 'Mayotte', 'YT', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (144, 'Mexico', 'MX', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (145, 'Micronesia, Federated States of', 'FM', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (146, 'Moldova, Republic of', 'MD', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (147, 'Monaco', 'MC', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (148, 'Mongolia', 'MN', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (149, 'Montenegro', 'ME', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (150, 'Montserrat', 'MS', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (151, 'Morocco', 'MA', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (152, 'Mozambique', 'MZ', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (153, 'Myanmar', 'MM', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (154, 'Namibia', 'NA', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (155, 'Nauru', 'NR', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (156, 'Nepal', 'NP', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (157, 'Netherlands', 'NL', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (158, 'New Caledonia', 'NC', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (159, 'New Zealand', 'NZ', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (160, 'Nicaragua', 'NI', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (161, 'Niger', 'NE', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (162, 'Nigeria', 'NG', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (163, 'Niue', 'NU', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (164, 'Norfolk Island', 'NF', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (165, 'Northern Mariana Islands', 'MP', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (166, 'Norway', 'NO', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (167, 'Oman', 'OM', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (168, 'Pakistan', 'PK', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (169, 'Palau', 'PW', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (170, 'Palestinian Territory, Occupied', 'PS', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (171, 'Panama', 'PA', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (172, 'Papua New Guinea', 'PG', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (173, 'Paraguay', 'PY', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (174, 'Peru', 'PE', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (175, 'Philippines', 'PH', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (176, 'Pitcairn', 'PN', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (177, 'Poland', 'PL', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (178, 'Portugal', 'PT', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (179, 'Puerto Rico', 'PR', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (180, 'Qatar', 'QA', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (181, 'Réunion', 'RE', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (182, 'Romania', 'RO', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (183, 'Russian Federation', 'RU', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (184, 'Rwanda', 'RW', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (185, 'Saint Barthélemy', 'BL', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (186, 'Saint Helena', 'SH', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (187, 'Saint Kitts and Nevis', 'KN', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (188, 'Saint Lucia', 'LC', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (189, 'Saint Martin (French part)', 'MF', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (190, 'Saint Pierre and Miquelon', 'PM', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (191, 'Saint Vincent and the Grenadines', 'VC', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (192, 'Samoa', 'WS', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (193, 'San Marino', 'SM', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (194, 'Sao Tome and Principe', 'ST', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (195, 'Saudi Arabia', 'SA', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (196, 'Senegal', 'SN', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (197, 'Serbia', 'RS', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (198, 'Seychelles', 'SC', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (199, 'Sierra Leone', 'SL', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (200, 'Singapore', 'SG', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (201, 'Sint Maarten (Dutch part)', 'SX', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (202, 'Slovakia', 'SK', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (203, 'Slovenia', 'SI', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (204, 'Solomon Islands', 'SB', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (205, 'Somalia', 'SO', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (206, 'South Africa', 'ZA', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (207, 'South Georgia and the South Sandwich Islands', 'GS', 2);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (208, 'South Sudan', 'SS', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (209, 'Spain', 'ES', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (210, 'Sri Lanka', 'LK', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (211, 'Sudan', 'SD', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (212, 'Suriname', 'SR', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (213, 'Svalbard and Jan Mayen', 'SJ', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (214, 'Swaziland', 'SZ', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (215, 'Sweden', 'SE', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (216, 'Switzerland', 'CH', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (217, 'Syrian Arab Republic', 'SY', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (218, 'Taiwan, Province of China', 'TW', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (219, 'Tajikistan', 'TJ', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (220, 'Tanzania, United Republic of', 'TZ', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (221, 'Thailand', 'TH', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (222, 'Timor-Leste', 'TL', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (223, 'Togo', 'TG', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (224, 'Tokelau', 'TK', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (225, 'Tonga', 'TO', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (226, 'Trinidad and Tobago', 'TT', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (227, 'Tunisia', 'TN', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (228, 'Turkey', 'TR', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (229, 'Turkmenistan', 'TM', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (230, 'Turks and Caicos Islands', 'TC', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (231, 'Tuvalu', 'TV', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (232, 'Uganda', 'UG', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (233, 'Ukraine', 'UA', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (234, 'United Arab Emirates', 'AE', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (235, 'United Kingdom', 'GB', 5);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (236, 'United States', 'US', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (237, 'United States Minor Outlying Islands', 'UM', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (238, 'Uruguay', 'UY', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (239, 'Uzbekistan', 'UZ', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (240, 'Vanuatu', 'VU', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (241, 'Venezuela', 'VE', 7);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (242, 'Vietnam', 'VN', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (243, 'Virgin Islands, British', 'VG', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (244, 'Virgin Islands, U.S.', 'VI', 6);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (245, 'Wallis and Futuna', 'WF', 4);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (246, 'Western Sahara', 'EH', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (247, 'Yemen', 'YE', 3);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (248, 'Zambia', 'ZM', 1);
INSERT INTO `universitylist_country`(`id`, `name`, `short_name`, `continent_id`) VALUES (249, 'Zimbabwe', 'ZW', 1);
commit;