# Generated by Django 3.0.1 on 2020-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200221_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='club_activity',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discipline_competition',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='graduate_school',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ielts',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='research_experience',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_rank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='toefl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.BooleanField(null=True),
        ),
    ]
